/**
 * `@tradecraft/content-tools` — the dev-only content authoring tools.
 *
 * The package bundles the Pack Linter, the Preview CLI, the Coverage Report and
 * the offline Authoring Aid behind the `pnpm content` CLI. No runtime package
 * imports it (Req 16.1); it may import `content`, `engine`, `player-view` and
 * `llm`.
 *
 * Task 5.1 stands up the package, the CLI shell and the subcommand stubs. Tasks
 * 5.2–5.13 flesh out each tool.
 */

export {
  CONTENT_COMMANDS,
  USAGE,
  runCli,
  main,
  type CliResult,
  type ContentCommand,
} from './cli.js';

export {
  runLint,
  lint,
  LINT_RULES,
  RULES_BY_ID,
  NON_SUPPRESSIBLE_RULES,
  GENERIC_FIELD_RULES,
  buildReport,
  sortFindings,
  formatText,
  formatJson,
  exitCodeFor,
  readParsedPacks,
  fieldValues,
  collectFieldHits,
  collectSuppressions,
  applySuppressions,
  ruleForError,
  findingForError,
  type LintCliOptions,
  type LintOptions,
  type LintProfile,
  type LintReport,
  type LintRule,
  type LintFinding,
  type LintContext,
  type LintSeverity,
  type BaselineManifest,
  type ParsedPack,
  type ParsedFile,
  type FieldHit,
  type FieldCategory,
  type GenericFieldRule,
  type Suppression,
} from './lint/index.js';
export {
  runPreview,
  type PreviewCliOptions,
  type PreviewKind,
} from './preview/index.js';
export {
  runCoverage,
  coverage,
  coverageSeed,
  worldLocationSet,
  buildCoverageReport,
  eligibleForCity,
  requiredQueryMarginsForCity,
  staticBinderCount,
  flagFor,
  jaccard,
  meanPairwiseJaccard,
  sortRows,
  sortMargins,
  sortVariety,
  toMarkdown,
  toCsv,
  CSV_HEADER,
  DEFAULT_UNDERUSE,
  DEFAULT_VARIETY_TARGET,
  type CoverageCliOptions,
  type CoverageDeps,
  type CoverageOptions,
  type CoverageReport,
  type CoverageRow,
  type CoverageCell,
  type CoverageInputs,
  type CoverageFlag,
  type RequiredQueryMargin,
  type VarietyRow,
  type UsageCount,
  type EligibleByKind,
  type ContentId,
} from './coverage/index.js';
export {
  runAuthor,
  runPromote,
  runAuthorCore,
  runPromoteCore,
  buildPrompt,
  buildPromotedFile,
  collectPromptInputs,
  endpointDecision,
  isLocalEndpoint,
  parseAuthoringConfig,
  schemaForKind,
  draftPathFor,
  hashPrompt,
  AuthoringConfigSchema,
  type AuthorCliOptions,
  type AuthorClient,
  type AuthorRequest,
  type AuthorResult,
  type AuthorMessage,
  type AuthorCallOptions,
  type DraftSink,
  type AuthoringConfig,
  type EndpointDecision,
  type PromptInputs,
  type PromptMessages,
  type PromoteFs,
  type PromoteRequest,
  type PromoteResult,
} from './author/index.js';
