import { type Tree } from '@nx/devkit';
export declare const nxVersion: any;
export declare const minSupportedVitestVersion = "3.0.0";
export declare const vitestVersion = "~4.1.0";
export declare const vitestCoverageV8Version = "~4.1.0";
export declare const vitestCoverageIstanbulVersion = "~4.1.0";
export declare const viteVersion = "^8.0.0";
export declare const viteV7Version = "^7.0.0";
export declare const viteV6Version = "^6.0.0";
export declare const viteV5Version = "^5.0.0";
export declare const vitePluginReactVersion = "^6.0.0";
export declare const vitePluginReactV4Version = "^4.2.0";
export declare const vitePluginReactSwcVersion = "^4.3.0";
export declare const jsdomVersion = "^27.1.0";
export declare const vitePluginDtsVersion = "~4.5.0";
export declare const ajvVersion = "^8.0.0";
export declare const happyDomVersion = "^20.10.4";
export declare const edgeRuntimeVmVersion = "~3.0.2";
export declare const jitiVersion = "2.4.2";
export declare const analogVitestAngular = "~2.6.0";
type VitestVersions = {
    vitestVersion: string;
    vitestCoverageV8Version: string;
    vitestCoverageIstanbulVersion: string;
};
export declare function versions(tree: Tree): VitestVersions;
export declare function getInstalledVitestVersion(tree?: Tree): string | null;
export declare function getInstalledVitestMajorVersion(tree?: Tree): number | null;
export {};
